### PR TITLE
new keys + quote detection

### PR DESCRIPTION
**Pull request by barronwaffles**
I'm still not incredibly familiar with the pythonic way of doing things, so chances are there's a more efficient way of doing that partition.

### CODE REVIEW

**Comment by sepalani** [comment]
@barronwaffles That's not the proper way to use git. It's highly recommended to create a new branch on your fork and work on it for a Pull Request rather than working on your master branch (if you master git you can also do it on your master branch, if you really want to). Moreover, don't merge upstream/master to your master branch but rebase it instead when you want to catch up with the original project. If you don't, it will add your Merge commits into the repository and we don't want such thing as "Merge pull request #1 from **sepalani/master**" or "Merge remote-tracking branch '**upstream/master**'" in the main repository when someone creates a Pull Request.

Ideally, you should have done a PR for your keys and another one for your code. Doing, two separates PRs would have been more handy because one is code related while the other isn't.

Finally, I don't think your code is more efficient. Don't submit a PR that hasn't been tested and proved to be more efficient (especially code wise). As far as I can tell, replacing ```line[0] == '#'``` with ```line.partition('#')[0]``` isn't more efficient and is error prone. I check for the first character to be a ```#``` if so, skip it because it's a comment. Your code call partition which is like split but also return the separator in the tuple which is not what we want, line would be changed from a string to a tuple and I'm pretty sure the other checks will fail after that.

**Comment by barronwaffles** [comment]
Ah, rgr. Sorry about that - still catching up on quit a bit of git methodology + work-flow.

Oh, about the commit message - I should have been more explicit in that I think there's almost certainly a more efficient way of doing that partition : what I was aiming for is supporting comments on the same line as a data entry itself and it seemed to function with the test I provided to it.

**Comment by sepalani** [comment]
I don't see why we should allow (more) comments (on the same line). It will make the line bigger than 80 columns quite easily and it won't be as readable. It's also error prone and might add an extra space after the key which is bad. Fortunately, the ```.strip()``` calls get rid of that.

**Comment by barronwaffles** [comment]
Good call - I've always lent towards comments being everything after the delimiter but that does lend itself towards run-on lines. I'll clean up my fork and get some more keys out to you soon.

**Pull request closed without merging**
